// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package ocr

import (
	"syscall"
	"unsafe"

	"github.com/Rake-Pro/GoShareIt/platform/windows/winocr/internal/winrt/foundation"
	"github.com/Rake-Pro/GoShareIt/platform/windows/winocr/internal/winrt/foundation/collections"
	"github.com/Rake-Pro/GoShareIt/platform/windows/winocr/internal/winrt/globalization"
	"github.com/Rake-Pro/GoShareIt/platform/windows/winocr/internal/winrt/graphics/imaging"
	"github.com/go-ole/go-ole"
)

const SignatureOcrEngine string = "rc(Windows.Media.Ocr.OcrEngine;{5a14bc41-5b76-3140-b680-8825562683ac})"

type OcrEngine struct {
	ole.IUnknown
}

func (impl *OcrEngine) RecognizeAsync(bitmap *imaging.SoftwareBitmap) (*foundation.IAsyncOperation, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiOcrEngine))
	defer itf.Release()
	v := (*iOcrEngine)(unsafe.Pointer(itf))
	return v.RecognizeAsync(bitmap)
}

func (impl *OcrEngine) GetRecognizerLanguage() (*globalization.Language, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiOcrEngine))
	defer itf.Release()
	v := (*iOcrEngine)(unsafe.Pointer(itf))
	return v.GetRecognizerLanguage()
}

const GUIDiOcrEngine string = "5a14bc41-5b76-3140-b680-8825562683ac"
const SignatureiOcrEngine string = "{5a14bc41-5b76-3140-b680-8825562683ac}"

type iOcrEngine struct {
	ole.IInspectable
}

type iOcrEngineVtbl struct {
	ole.IInspectableVtbl

	RecognizeAsync        uintptr
	GetRecognizerLanguage uintptr
}

func (v *iOcrEngine) VTable() *iOcrEngineVtbl {
	return (*iOcrEngineVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iOcrEngine) RecognizeAsync(bitmap *imaging.SoftwareBitmap) (*foundation.IAsyncOperation, error) {
	var out *foundation.IAsyncOperation
	hr, _, _ := syscall.SyscallN(
		v.VTable().RecognizeAsync,
		uintptr(unsafe.Pointer(v)),      // this
		uintptr(unsafe.Pointer(bitmap)), // in imaging.SoftwareBitmap
		uintptr(unsafe.Pointer(&out)),   // out foundation.IAsyncOperation
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iOcrEngine) GetRecognizerLanguage() (*globalization.Language, error) {
	var out *globalization.Language
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetRecognizerLanguage,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out globalization.Language
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

const GUIDiOcrEngineStatics string = "5bffa85a-3384-3540-9940-699120d428a8"
const SignatureiOcrEngineStatics string = "{5bffa85a-3384-3540-9940-699120d428a8}"

type iOcrEngineStatics struct {
	ole.IInspectable
}

type iOcrEngineStaticsVtbl struct {
	ole.IInspectableVtbl

	OcrEngineGetMaxImageDimension              uintptr
	OcrEngineGetAvailableRecognizerLanguages   uintptr
	OcrEngineIsLanguageSupported               uintptr
	OcrEngineTryCreateFromLanguage             uintptr
	OcrEngineTryCreateFromUserProfileLanguages uintptr
}

func (v *iOcrEngineStatics) VTable() *iOcrEngineStaticsVtbl {
	return (*iOcrEngineStaticsVtbl)(unsafe.Pointer(v.RawVTable))
}

func OcrEngineGetMaxImageDimension() (uint32, error) {
	inspectable, err := ole.RoGetActivationFactory("Windows.Media.Ocr.OcrEngine", ole.NewGUID(GUIDiOcrEngineStatics))
	if err != nil {
		return 0, err
	}
	v := (*iOcrEngineStatics)(unsafe.Pointer(inspectable))

	var out uint32
	hr, _, _ := syscall.SyscallN(
		v.VTable().OcrEngineGetMaxImageDimension,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out uint32
	)

	if hr != 0 {
		return 0, ole.NewError(hr)
	}

	return out, nil
}

func OcrEngineGetAvailableRecognizerLanguages() (*collections.IVectorView, error) {
	inspectable, err := ole.RoGetActivationFactory("Windows.Media.Ocr.OcrEngine", ole.NewGUID(GUIDiOcrEngineStatics))
	if err != nil {
		return nil, err
	}
	v := (*iOcrEngineStatics)(unsafe.Pointer(inspectable))

	var out *collections.IVectorView
	hr, _, _ := syscall.SyscallN(
		v.VTable().OcrEngineGetAvailableRecognizerLanguages,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out collections.IVectorView
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func OcrEngineIsLanguageSupported(language *globalization.Language) (bool, error) {
	inspectable, err := ole.RoGetActivationFactory("Windows.Media.Ocr.OcrEngine", ole.NewGUID(GUIDiOcrEngineStatics))
	if err != nil {
		return false, err
	}
	v := (*iOcrEngineStatics)(unsafe.Pointer(inspectable))

	var out bool
	hr, _, _ := syscall.SyscallN(
		v.VTable().OcrEngineIsLanguageSupported,
		uintptr(unsafe.Pointer(v)),        // this
		uintptr(unsafe.Pointer(language)), // in globalization.Language
		uintptr(unsafe.Pointer(&out)),     // out bool
	)

	if hr != 0 {
		return false, ole.NewError(hr)
	}

	return out, nil
}

func OcrEngineTryCreateFromLanguage(language *globalization.Language) (*OcrEngine, error) {
	inspectable, err := ole.RoGetActivationFactory("Windows.Media.Ocr.OcrEngine", ole.NewGUID(GUIDiOcrEngineStatics))
	if err != nil {
		return nil, err
	}
	v := (*iOcrEngineStatics)(unsafe.Pointer(inspectable))

	var out *OcrEngine
	hr, _, _ := syscall.SyscallN(
		v.VTable().OcrEngineTryCreateFromLanguage,
		uintptr(unsafe.Pointer(v)),        // this
		uintptr(unsafe.Pointer(language)), // in globalization.Language
		uintptr(unsafe.Pointer(&out)),     // out OcrEngine
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func OcrEngineTryCreateFromUserProfileLanguages() (*OcrEngine, error) {
	inspectable, err := ole.RoGetActivationFactory("Windows.Media.Ocr.OcrEngine", ole.NewGUID(GUIDiOcrEngineStatics))
	if err != nil {
		return nil, err
	}
	v := (*iOcrEngineStatics)(unsafe.Pointer(inspectable))

	var out *OcrEngine
	hr, _, _ := syscall.SyscallN(
		v.VTable().OcrEngineTryCreateFromUserProfileLanguages,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out OcrEngine
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}
