// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package ocr

import (
	"syscall"
	"unsafe"

	"github.com/Rake-Pro/GoShareIt/platform/windows/winocr/internal/winrt/foundation/collections"
	"github.com/go-ole/go-ole"
)

const SignatureOcrLine string = "rc(Windows.Media.Ocr.OcrLine;{0043a16f-e31f-3a24-899c-d444bd088124})"

type OcrLine struct {
	ole.IUnknown
}

func (impl *OcrLine) GetWords() (*collections.IVectorView, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiOcrLine))
	defer itf.Release()
	v := (*iOcrLine)(unsafe.Pointer(itf))
	return v.GetWords()
}

func (impl *OcrLine) GetText() (string, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiOcrLine))
	defer itf.Release()
	v := (*iOcrLine)(unsafe.Pointer(itf))
	return v.GetText()
}

const GUIDiOcrLine string = "0043a16f-e31f-3a24-899c-d444bd088124"
const SignatureiOcrLine string = "{0043a16f-e31f-3a24-899c-d444bd088124}"

type iOcrLine struct {
	ole.IInspectable
}

type iOcrLineVtbl struct {
	ole.IInspectableVtbl

	GetWords uintptr
	GetText  uintptr
}

func (v *iOcrLine) VTable() *iOcrLineVtbl {
	return (*iOcrLineVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iOcrLine) GetWords() (*collections.IVectorView, error) {
	var out *collections.IVectorView
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetWords,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out collections.IVectorView
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iOcrLine) GetText() (string, error) {
	var outHStr ole.HString
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetText,
		uintptr(unsafe.Pointer(v)),        // this
		uintptr(unsafe.Pointer(&outHStr)), // out string
	)

	if hr != 0 {
		return "", ole.NewError(hr)
	}

	out := outHStr.String()
	ole.DeleteHString(outHStr)
	return out, nil
}
