// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package ocr

import (
	"syscall"
	"unsafe"

	"github.com/Rake-Pro/GoShareIt/platform/windows/winocr/internal/winrt/foundation"
	"github.com/Rake-Pro/GoShareIt/platform/windows/winocr/internal/winrt/foundation/collections"
	"github.com/go-ole/go-ole"
)

const SignatureOcrResult string = "rc(Windows.Media.Ocr.OcrResult;{9bd235b2-175b-3d6a-92e2-388c206e2f63})"

type OcrResult struct {
	ole.IUnknown
}

func (impl *OcrResult) GetLines() (*collections.IVectorView, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiOcrResult))
	defer itf.Release()
	v := (*iOcrResult)(unsafe.Pointer(itf))
	return v.GetLines()
}

func (impl *OcrResult) GetTextAngle() (*foundation.IReference, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiOcrResult))
	defer itf.Release()
	v := (*iOcrResult)(unsafe.Pointer(itf))
	return v.GetTextAngle()
}

func (impl *OcrResult) GetText() (string, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiOcrResult))
	defer itf.Release()
	v := (*iOcrResult)(unsafe.Pointer(itf))
	return v.GetText()
}

const GUIDiOcrResult string = "9bd235b2-175b-3d6a-92e2-388c206e2f63"
const SignatureiOcrResult string = "{9bd235b2-175b-3d6a-92e2-388c206e2f63}"

type iOcrResult struct {
	ole.IInspectable
}

type iOcrResultVtbl struct {
	ole.IInspectableVtbl

	GetLines     uintptr
	GetTextAngle uintptr
	GetText      uintptr
}

func (v *iOcrResult) VTable() *iOcrResultVtbl {
	return (*iOcrResultVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iOcrResult) GetLines() (*collections.IVectorView, error) {
	var out *collections.IVectorView
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetLines,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out collections.IVectorView
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iOcrResult) GetTextAngle() (*foundation.IReference, error) {
	var out *foundation.IReference
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetTextAngle,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out foundation.IReference
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iOcrResult) GetText() (string, error) {
	var outHStr ole.HString
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetText,
		uintptr(unsafe.Pointer(v)),        // this
		uintptr(unsafe.Pointer(&outHStr)), // out string
	)

	if hr != 0 {
		return "", ole.NewError(hr)
	}

	out := outHStr.String()
	ole.DeleteHString(outHStr)
	return out, nil
}
