// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package ocr

import (
	"syscall"
	"unsafe"

	"github.com/Rake-Pro/GoShareIt/platform/windows/winocr/internal/winrt/foundation"
	"github.com/go-ole/go-ole"
)

const SignatureOcrWord string = "rc(Windows.Media.Ocr.OcrWord;{3c2a477a-5cd9-3525-ba2a-23d1e0a68a1d})"

type OcrWord struct {
	ole.IUnknown
}

func (impl *OcrWord) GetBoundingRect() (foundation.Rect, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiOcrWord))
	defer itf.Release()
	v := (*iOcrWord)(unsafe.Pointer(itf))
	return v.GetBoundingRect()
}

func (impl *OcrWord) GetText() (string, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiOcrWord))
	defer itf.Release()
	v := (*iOcrWord)(unsafe.Pointer(itf))
	return v.GetText()
}

const GUIDiOcrWord string = "3c2a477a-5cd9-3525-ba2a-23d1e0a68a1d"
const SignatureiOcrWord string = "{3c2a477a-5cd9-3525-ba2a-23d1e0a68a1d}"

type iOcrWord struct {
	ole.IInspectable
}

type iOcrWordVtbl struct {
	ole.IInspectableVtbl

	GetBoundingRect uintptr
	GetText         uintptr
}

func (v *iOcrWord) VTable() *iOcrWordVtbl {
	return (*iOcrWordVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iOcrWord) GetBoundingRect() (foundation.Rect, error) {
	var out foundation.Rect
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetBoundingRect,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out foundation.Rect
	)

	if hr != 0 {
		return foundation.Rect{}, ole.NewError(hr)
	}

	return out, nil
}

func (v *iOcrWord) GetText() (string, error) {
	var outHStr ole.HString
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetText,
		uintptr(unsafe.Pointer(v)),        // this
		uintptr(unsafe.Pointer(&outHStr)), // out string
	)

	if hr != 0 {
		return "", ole.NewError(hr)
	}

	out := outHStr.String()
	ole.DeleteHString(outHStr)
	return out, nil
}
