// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package cryptography

import (
	"syscall"
	"unsafe"

	"github.com/Rake-Pro/GoShareIt/platform/windows/winocr/internal/winrt/storage/streams"
	"github.com/go-ole/go-ole"
)

const GUIDiCryptographicBufferStatics string = "320b7e22-3cb0-4cdf-8663-1d28910065eb"
const SignatureiCryptographicBufferStatics string = "{320b7e22-3cb0-4cdf-8663-1d28910065eb}"

type iCryptographicBufferStatics struct {
	ole.IInspectable
}

type iCryptographicBufferStaticsVtbl struct {
	ole.IInspectableVtbl

	CryptographicBufferCompare                uintptr
	CryptographicBufferGenerateRandom         uintptr
	CryptographicBufferGenerateRandomNumber   uintptr
	CryptographicBufferCreateFromByteArray    uintptr
	CryptographicBufferCopyToByteArray        uintptr
	CryptographicBufferDecodeFromHexString    uintptr
	CryptographicBufferEncodeToHexString      uintptr
	CryptographicBufferDecodeFromBase64String uintptr
	CryptographicBufferEncodeToBase64String   uintptr
	CryptographicBufferConvertStringToBinary  uintptr
	CryptographicBufferConvertBinaryToString  uintptr
}

func (v *iCryptographicBufferStatics) VTable() *iCryptographicBufferStaticsVtbl {
	return (*iCryptographicBufferStaticsVtbl)(unsafe.Pointer(v.RawVTable))
}

func CryptographicBufferCreateFromByteArray(valueSize uint32, value []uint8) (*streams.IBuffer, error) {
	inspectable, err := ole.RoGetActivationFactory("Windows.Security.Cryptography.CryptographicBuffer", ole.NewGUID(GUIDiCryptographicBufferStatics))
	if err != nil {
		return nil, err
	}
	v := (*iCryptographicBufferStatics)(unsafe.Pointer(inspectable))

	var out *streams.IBuffer
	hr, _, _ := syscall.SyscallN(
		v.VTable().CryptographicBufferCreateFromByteArray,
		uintptr(unsafe.Pointer(v)),         // this
		uintptr(valueSize),                 // in uint32
		uintptr(unsafe.Pointer(&value[0])), // in uint8
		uintptr(unsafe.Pointer(&out)),      // out streams.IBuffer
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}
