// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package imaging

type BitmapPixelFormat int32

const SignatureBitmapPixelFormat string = "enum(Windows.Graphics.Imaging.BitmapPixelFormat;i4)"

const (
	BitmapPixelFormatUnknown BitmapPixelFormat = 0
	BitmapPixelFormatRgba16  BitmapPixelFormat = 12
	BitmapPixelFormatRgba8   BitmapPixelFormat = 30
	BitmapPixelFormatGray16  BitmapPixelFormat = 57
	BitmapPixelFormatGray8   BitmapPixelFormat = 62
	BitmapPixelFormatBgra8   BitmapPixelFormat = 87
	BitmapPixelFormatNv12    BitmapPixelFormat = 103
	BitmapPixelFormatP010    BitmapPixelFormat = 104
	BitmapPixelFormatYuy2    BitmapPixelFormat = 107
)
