// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package imaging

type BitmapAlphaMode int32

const SignatureBitmapAlphaMode string = "enum(Windows.Graphics.Imaging.BitmapAlphaMode;i4)"

const (
	BitmapAlphaModePremultiplied BitmapAlphaMode = 0
	BitmapAlphaModeStraight      BitmapAlphaMode = 1
	BitmapAlphaModeIgnore        BitmapAlphaMode = 2
)
