// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package imaging

import (
	"syscall"
	"unsafe"

	"github.com/Rake-Pro/GoShareIt/platform/windows/winocr/internal/winrt/foundation"
	"github.com/Rake-Pro/GoShareIt/platform/windows/winocr/internal/winrt/storage/streams"
	"github.com/go-ole/go-ole"
)

const SignatureSoftwareBitmap string = "rc(Windows.Graphics.Imaging.SoftwareBitmap;{689e0708-7eef-483f-963f-da938818e073})"

type SoftwareBitmap struct {
	ole.IUnknown
}

func (impl *SoftwareBitmap) GetPixelWidth() (int32, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiSoftwareBitmap))
	defer itf.Release()
	v := (*iSoftwareBitmap)(unsafe.Pointer(itf))
	return v.GetPixelWidth()
}

func (impl *SoftwareBitmap) GetPixelHeight() (int32, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiSoftwareBitmap))
	defer itf.Release()
	v := (*iSoftwareBitmap)(unsafe.Pointer(itf))
	return v.GetPixelHeight()
}

func (impl *SoftwareBitmap) Close() error {
	itf := impl.MustQueryInterface(ole.NewGUID(foundation.GUIDIClosable))
	defer itf.Release()
	v := (*foundation.IClosable)(unsafe.Pointer(itf))
	return v.Close()
}

const GUIDiSoftwareBitmap string = "689e0708-7eef-483f-963f-da938818e073"
const SignatureiSoftwareBitmap string = "{689e0708-7eef-483f-963f-da938818e073}"

type iSoftwareBitmap struct {
	ole.IInspectable
}

type iSoftwareBitmapVtbl struct {
	ole.IInspectableVtbl

	GetBitmapPixelFormat uintptr
	GetBitmapAlphaMode   uintptr
	GetPixelWidth        uintptr
	GetPixelHeight       uintptr
	GetIsReadOnly        uintptr
	SetDpiX              uintptr
	GetDpiX              uintptr
	SetDpiY              uintptr
	GetDpiY              uintptr
	LockBuffer           uintptr
	CopyTo               uintptr
	CopyFromBuffer       uintptr
	CopyToBuffer         uintptr
	GetReadOnlyView      uintptr
}

func (v *iSoftwareBitmap) VTable() *iSoftwareBitmapVtbl {
	return (*iSoftwareBitmapVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iSoftwareBitmap) GetPixelWidth() (int32, error) {
	var out int32
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetPixelWidth,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out int32
	)

	if hr != 0 {
		return 0, ole.NewError(hr)
	}

	return out, nil
}

func (v *iSoftwareBitmap) GetPixelHeight() (int32, error) {
	var out int32
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetPixelHeight,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out int32
	)

	if hr != 0 {
		return 0, ole.NewError(hr)
	}

	return out, nil
}

const GUIDiSoftwareBitmapStatics string = "df0385db-672f-4a9d-806e-c2442f343e86"
const SignatureiSoftwareBitmapStatics string = "{df0385db-672f-4a9d-806e-c2442f343e86}"

type iSoftwareBitmapStatics struct {
	ole.IInspectable
}

type iSoftwareBitmapStaticsVtbl struct {
	ole.IInspectableVtbl

	SoftwareBitmapCopy                                uintptr
	SoftwareBitmapConvert                             uintptr
	SoftwareBitmapConvertWithAlpha                    uintptr
	SoftwareBitmapCreateCopyFromBuffer                uintptr
	SoftwareBitmapCreateCopyWithAlphaFromBuffer       uintptr
	SoftwareBitmapCreateCopyFromSurfaceAsync          uintptr
	SoftwareBitmapCreateCopyWithAlphaFromSurfaceAsync uintptr
}

func (v *iSoftwareBitmapStatics) VTable() *iSoftwareBitmapStaticsVtbl {
	return (*iSoftwareBitmapStaticsVtbl)(unsafe.Pointer(v.RawVTable))
}

func SoftwareBitmapCreateCopyFromBuffer(source *streams.IBuffer, format BitmapPixelFormat, width int32, height int32) (*SoftwareBitmap, error) {
	inspectable, err := ole.RoGetActivationFactory("Windows.Graphics.Imaging.SoftwareBitmap", ole.NewGUID(GUIDiSoftwareBitmapStatics))
	if err != nil {
		return nil, err
	}
	v := (*iSoftwareBitmapStatics)(unsafe.Pointer(inspectable))

	var out *SoftwareBitmap
	hr, _, _ := syscall.SyscallN(
		v.VTable().SoftwareBitmapCreateCopyFromBuffer,
		uintptr(unsafe.Pointer(v)),      // this
		uintptr(unsafe.Pointer(source)), // in streams.IBuffer
		uintptr(format),                 // in BitmapPixelFormat
		uintptr(width),                  // in int32
		uintptr(height),                 // in int32
		uintptr(unsafe.Pointer(&out)),   // out SoftwareBitmap
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}
