// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package globalization

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
)

const SignatureLanguage string = "rc(Windows.Globalization.Language;{ea79a752-f7c2-4265-b1bd-c4dec4e4f080})"

type Language struct {
	ole.IUnknown
}

func (impl *Language) GetLanguageTag() (string, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiLanguage))
	defer itf.Release()
	v := (*iLanguage)(unsafe.Pointer(itf))
	return v.GetLanguageTag()
}

func (impl *Language) GetDisplayName() (string, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiLanguage))
	defer itf.Release()
	v := (*iLanguage)(unsafe.Pointer(itf))
	return v.GetDisplayName()
}

const GUIDiLanguage string = "ea79a752-f7c2-4265-b1bd-c4dec4e4f080"
const SignatureiLanguage string = "{ea79a752-f7c2-4265-b1bd-c4dec4e4f080}"

type iLanguage struct {
	ole.IInspectable
}

type iLanguageVtbl struct {
	ole.IInspectableVtbl

	GetLanguageTag uintptr
	GetDisplayName uintptr
	GetNativeName  uintptr
	GetScript      uintptr
}

func (v *iLanguage) VTable() *iLanguageVtbl {
	return (*iLanguageVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iLanguage) GetLanguageTag() (string, error) {
	var outHStr ole.HString
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetLanguageTag,
		uintptr(unsafe.Pointer(v)),        // this
		uintptr(unsafe.Pointer(&outHStr)), // out string
	)

	if hr != 0 {
		return "", ole.NewError(hr)
	}

	out := outHStr.String()
	ole.DeleteHString(outHStr)
	return out, nil
}

func (v *iLanguage) GetDisplayName() (string, error) {
	var outHStr ole.HString
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetDisplayName,
		uintptr(unsafe.Pointer(v)),        // this
		uintptr(unsafe.Pointer(&outHStr)), // out string
	)

	if hr != 0 {
		return "", ole.NewError(hr)
	}

	out := outHStr.String()
	ole.DeleteHString(outHStr)
	return out, nil
}

const GUIDiLanguageExtensionSubtags string = "7d7daf45-368d-4364-852b-dec927037b85"
const SignatureiLanguageExtensionSubtags string = "{7d7daf45-368d-4364-852b-dec927037b85}"

type iLanguageExtensionSubtags struct {
	ole.IInspectable
}

type iLanguageExtensionSubtagsVtbl struct {
	ole.IInspectableVtbl

	GetExtensionSubtags uintptr
}

func (v *iLanguageExtensionSubtags) VTable() *iLanguageExtensionSubtagsVtbl {
	return (*iLanguageExtensionSubtagsVtbl)(unsafe.Pointer(v.RawVTable))
}

const GUIDiLanguage2 string = "6a47e5b5-d94d-4886-a404-a5a5b9d5b494"
const SignatureiLanguage2 string = "{6a47e5b5-d94d-4886-a404-a5a5b9d5b494}"

type iLanguage2 struct {
	ole.IInspectable
}

type iLanguage2Vtbl struct {
	ole.IInspectableVtbl

	GetLayoutDirection uintptr
}

func (v *iLanguage2) VTable() *iLanguage2Vtbl {
	return (*iLanguage2Vtbl)(unsafe.Pointer(v.RawVTable))
}

const GUIDiLanguage3 string = "c6af3d10-641a-5ba4-bb43-5e12aed75954"
const SignatureiLanguage3 string = "{c6af3d10-641a-5ba4-bb43-5e12aed75954}"

type iLanguage3 struct {
	ole.IInspectable
}

type iLanguage3Vtbl struct {
	ole.IInspectableVtbl

	GetAbbreviatedName uintptr
}

func (v *iLanguage3) VTable() *iLanguage3Vtbl {
	return (*iLanguage3Vtbl)(unsafe.Pointer(v.RawVTable))
}
